language: cpp
compiler: gcc
dist: disco

before_install:
  # C++17
  - sudo apt-get update

install:
  # C++17
  - sudo apt-get install -qq gcc uthash-dev

script:
  - make -C ai

after_success:
  - bash comment_pr.sh
